name: "Novo artigo (publicação automática)"
description: "Preencha e envie. O blog publica sozinho."
title: "[Artigo] "
labels:
  - "novo-artigo"

body:
  - type: input
    id: titulo
    attributes:
      label: "Título"
      description: "Digite o título do artigo."
      placeholder: "Ex: Tendências do mercado em 2026"
    validations:
      required: true

  - type: input
    id: autor
    attributes:
      label: "Autor"
      description: "Nome do autor que assina o artigo."
      placeholder: "Ex: José Paulo Cavalcanti"
    validations:
      required: true

  - type: input
    id: data
    attributes:
      label: "Data"
      description: "Use AAAA-MM-DD (ex: 2025-12-28) ou DD/MM/AAAA (ex: 28/12/2025)."
      placeholder: "2025-12-28"
    validations:
      required: true

  - type: input
    id: categoria
    attributes:
      label: "Categoria"
      description: "Ex: Artigos, Institucional, Notícias, Opinião."
      placeholder: "Artigos"
    validations:
      required: true

  - type: textarea
    id: resumo
    attributes:
      label: "Resumo"
      description: "Escreva um resumo curto (sem '1–2 frases')."
      placeholder: "Resumo curto do artigo..."
    validations:
      required: true

  - type: textarea
    id: texto
    attributes:
      label: "Texto do artigo"
      description: "Separe parágrafos com uma linha em branco."
      placeholder: "Cole o texto aqui..."
    validations:
      required: true
